### ISSUE TITLE
Registro de usuário

### ISSUE THREAD

**Issue by CaioAlexndre** [CaioAlexndre/Etec-DemoDay#1]
A api deve registrar os usuários, fazendo a verificação se os mesmos estão 

1. já existentes 
2. banidos ou com algum tipo de restrição interna ou externa 
3. se seguiram corretamente as instruções de formato de login e senha.

**Comment by Fbdesouza** [comment]
Esse eu faço

**Comment by Fbdesouza** [comment]
[JS_Registro do Usuario.txt](https://github.com/user-attachments/files/15878358/JS_Registro.do.Usuario.txt)
[Registro de usuário.txt](https://github.com/user-attachments/files/15878359/Registro.de.usuario.txt)
