### ISSUE TITLE
Interface do usuário

### ISSUE THREAD

**Issue by CaioAlexndre** [CaioAlexndre/Etec-DemoDay#8]
1. Coloque a foto de usuário, não houve coloque um placeholder.
2.Coloque um botão de "configuração"
3.Coloque um botão de "veja seu perfil"
          coloque quantidade de vitorias, tempo jogado e principal disciplina.
4.Central de ajuda

**Comment by JessicaSabbatini** [comment]
Fiz essa parte, espero que esteja ok :)
